--- 

name: Cowsay Workflow

on:
    push:
        branches:
            - main
    
jobs:
    cowsay-job:
        runs-on: ubuntu-latest
    
    steps:
        - name: Cowsay Hello
        run:
            sudo apt-get update
            sudo apt-get install -y cowsay
            cowsay "Hello from Github Actions"
